title: Muflone
default_lang: en
author:
  name: Muflone
  email: muflone@muflone.com
taxonomies:
  - category
  - tag
metadata:
  description: 'My projects, my news and my stuff'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /gwakeonlan/wol_bios: /gwakeonlan/wol/bios
  /gwakeonlan/wol_os: /gwakeonlan/wol/os
  /gwakeonlan/wol_requirements: /gwakeonlan/wol/requirements
blog:
  route: /blog
