title: Muflone
author:
  name: Muflone
  email: muflone@muflone.com
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /gespeaker/install: /gespeaker/installation
blog:
  route: /blog
