analytics_id: UA-44039396-3
analytics_username: muflone.com
home_product: home
icon_footer: android-icon-48x48.png
products:
  -
    name: Gespeaker
    short_name: gespeaker
    github: 'https://github.com/muflone/gespeaker'
    translations: 'https://www.transifex.com/projects/p/gespeaker/'
    languages:
      - english
      - french
      - italian
      - spanish
      - catalan
      - dutch
      - polish
      - bulgarian
      - faroese
      - german
      - arabic
      - greek
      - vietnamese
      - turkish
      - chinese
    versions:
      -
        version: 0.8.6
        shortver: v086
        packages: [{ type: source, filename: gespeaker-0.8.6.tar.gz, size: 149, md5sum: DCCFED9A29393692E3FAB334541BC996, sources: [muflone, github] }, { type: debian, filename: gespeaker_0.8.6-1_all.deb, size: 123, md5sum: 429787EC6621F6836B5287583F5E6029, sources: [muflone, github] }, { type: archlinux, filename: gespeaker-0.8.6-1-any.pkg.tar.xz, size: 124, md5sum: 4B18FBD1178B151AE18D4FFA42893354, sources: [muflone, github, archlinux] }, { type: archlinux_aur, filename: gespeaker-git, size: 0, md5sum: '-', sources: [aur] }]
      -
        version: 0.8.5
        shortver: v085
        packages: [{ type: source, filename: gespeaker-0.8.5.tar.gz, size: 148, md5sum: 5D97DED1B867C5E3D83F7D31E54B9628, sources: [muflone, github] }, { type: debian, filename: gespeaker_0.8.5-2_all.deb, size: 122, md5sum: 40A5D32F4F87EEE47B09D8E1B6BD2A82, sources: [muflone, github] }, { type: archlinux, filename: gespeaker-0.8.5-1-any.pkg.tar.xz, size: 122, md5sum: 960C0FBE1E596A122635C4744F4BBB0E, sources: [muflone, github] }]
      -
        version: 0.8.4
        shortver: v084
        packages: [{ type: source, filename: gespeaker-0.8.4.tar.gz, size: 145, md5sum: 63C7A8B9EF3DB4340EB197E4860DC244, sources: [muflone, github] }, { type: debian, filename: gespeaker_0.8.4-1_all.deb, size: 122, md5sum: C13EF8F8CD54BD01D313B2B5DB724078, sources: [muflone, github] }, { type: archlinux, filename: gespeaker-0.8.4-1-any.pkg.tar.xz, size: 120, md5sum: D1772D76588206F3359B7082F24AE6EB, sources: [muflone, github] }]
      -
        version: 0.8.3
        shortver: v083
        packages: [{ type: source, filename: gespeaker-0.8.3.tar.gz, size: 144, md5sum: 3BB5F54810CB875C55A1A4E9401213C6, sources: [muflone, github] }, { type: debian, filename: gespeaker_0.8.3-1_all.deb, size: 121, md5sum: 14834B2E9A3DE691781E83171FBC0CFE, sources: [muflone, github] }, { type: archlinux, filename: gespeaker-0.8.3-1-any.pkg.tar.xz, size: 120, md5sum: A1AFF7C06637A9950B80D22FF61E77CD, sources: [muflone, github] }]
      -
        version: 0.8.2
        shortver: v082
        packages: [{ type: source, filename: gespeaker-0.8.2.tar.gz, size: 142, md5sum: 12C74AB7858C818D0EA12CF0AD4A4FD8, sources: [muflone, github] }, { type: debian, filename: gespeaker_0.8.2-1_all.deb, size: 140, md5sum: FAA3BEE358D295B84480C8F5ADEAD1AE, sources: [muflone, github] }, { type: archlinux, filename: gespeaker-0.8.2-1-any.pkg.tar.xz, size: 116, md5sum: F24C87CE159946FBEFEFB0A2A854D88F, sources: [muflone, github] }]
  -
    name: gWakeOnLan
    short_name: gwakeonlan
    github: 'https://github.com/muflone/gwakeonlan'
    translations: 'https://www.transifex.com/projects/p/gwakeonlan/'
    languages:
      - english
      - french
      - italian
      - hebrew
      - spanish
      - german
      - russian
      - basque
      - dutch
      - polish
      - portoguese
      - slovak
      - slovenian
      - turkish
      - bulgarian
    versions:
      -
        version: 0.6.2
        shortver: v062
        packages: [{ type: source, filename: gwakeonlan-0.6.2.tar.gz, size: 85, md5sum: CCDC29789E9A9233631D4E2D403B5797, sources: [muflone, github] }, { type: archlinux, filename: gwakeonlan-0.6.2-1-any.pkg.tar.xz, size: 86, md5sum: A21AAFF372DEB5FE06990D5622EBC68E, sources: [muflone, github, archlinux] }, { type: archlinux_aur, filename: gwakeonlan-git, size: 0, md5sum: '-', sources: [aur] }]
      -
        version: 0.6.1
        shortver: v061
        packages: [{ type: source, filename: gwakeonlan-0.6.1.tar.gz, size: 83, md5sum: 3B4D50F2B1FED2260F36DE492ED1E84F, sources: [muflone, github] }, { type: archlinux, filename: gwakeonlan-0.6.1-1-any.pkg.tar.xz, size: 85, md5sum: 339C0C49E7ED56EBF23F6C483FE562FB, sources: [muflone, github] }]
      -
        version: '0.6'
        shortver: v060
        packages: [{ type: source, filename: gwakeonlan-0.6.tar.gz, size: 83, md5sum: 45308DC3DF2ACB26968F3BEDCC0C9A52, sources: [muflone, github] }, { type: archlinux, filename: gwakeonlan-0.6-2-any.pkg.tar.xz, size: 85, md5sum: E217BF6E30A899884E55972168FE52C8, sources: [muflone, github] }]
      -
        version: 0.5.1
        shortver: v051
        packages: [{ type: source, filename: gwakeonlan-0.5.1.tar.gz, size: 30, md5sum: 68BDE5820DB9C122EDF9E221797049FA, sources: [muflone, github] }, { type: debian, filename: gwakeonlan_0.5.1-1_all.deb, size: 25, md5sum: D267F4148769D66E5AF3D2CA93EEF8E2, sources: [muflone, github] }, { type: archlinux, filename: gwakeonlan-0.5.1-3-any.pkg.tar.xz, size: 27, md5sum: 9A6FE2FDF58AA7C72A7B4ABFE9A9704A, sources: [muflone, github] }]
  -
    name: gExtractWinIcons
    short_name: gextractwinicons
    github: 'https://github.com/muflone/gextractwinicons'
    translations: 'https://www.transifex.com/projects/p/gextractwinicons/'
    languages:
      - english
      - french
      - italian
      - hebrew
      - spanish
      - russian
      - catalan
      - bulgarian
    versions:
      -
        version: 0.4.1
        shortver: v041
        packages: [{ type: source, filename: gextractwinicons-0.4.1.tar.gz, size: 63, md5sum: 52A3AD3CE477A9C6B9165D47510AF238, sources: [muflone, github] }, { type: archlinux, filename: gextractwinicons-0.4.1-1-any.pkg.tar.xz, size: 64, md5sum: 176F717F23897A1F4BF6B3A09D120CB0, sources: [muflone, github] }, { type: archlinux_aur, filename: gextractwinicons, size: 0, md5sum: '-', sources: [aur] }, { type: archlinux_aur, filename: gextractwinicons-git, size: 0, md5sum: '-', sources: [aur] }]
      -
        version: '0.4'
        shortver: v040
        packages: [{ type: source, filename: gextractwinicons-0.4.tar.gz, size: 61, md5sum: E9A6A6CDC7FC6B10E821B3790CA58E39, sources: [muflone, github] }, { type: archlinux, filename: gextractwinicons-0.4-1-any.pkg.tar.xz, size: 61, md5sum: 9654C8B8EF33F46F4C07EB5F0A88EB5A, sources: [muflone, github] }]
      -
        version: 0.3.1
        shortver: v031
        packages: [{ type: source, filename: gextractwinicons-0.3.1.tar.gz, size: 24, md5sum: 1598568B87D9FEA2DE96D79A87EE68C5, sources: [muflone, github] }, { type: debian, filename: gextractwinicons_0.3.1-1_all.deb, size: 19, md5sum: 914D5713B9121FBC7A130231D254F34A, sources: [muflone, github] }, { type: archlinux, filename: gextractwinicons-0.3.1-1-any.pkg.tar.xz, size: 17, md5sum: BC2243D00E9AD2A8141DBF1B5B126F62, sources: [muflone, github] }]
  -
    name: BlueWho
    short_name: bluewho
    github: 'https://github.com/muflone/bluewho'
    translations: 'https://www.transifex.com/projects/p/bluewho/'
    languages:
      - english
      - french
      - italian
      - german
      - hungarian
      - russian
      - spanish
      - bulgarian
      - danish
      - colombian
      - hebrew
      - dutch
      - turkish
    versions:
      -
        version: 0.2.1
        shortver: v021
        packages: [{ type: source, filename: bluewho-0.2.1.tar.gz, size: 328, md5sum: DF8AB67E21081BCDC3261596F56BC220, sources: [muflone, github] }, { type: archlinux, filename: bluewho-0.2.1-1-any.pkg.tar.xz, size: 320, md5sum: 5A4547E00A975143D39F6C47A6FFB32E, sources: [muflone, github] }, { type: archlinux_aur, filename: bluewho, size: 0, md5sum: '-', sources: [aur] }, { type: archlinux_aur, filename: bluewho-git, size: 0, md5sum: '-', sources: [aur] }]
      -
        version: '0.2'
        shortver: v020
        packages: [{ type: source, filename: bluewho-0.2.tar.gz, size: 318, md5sum: 658C4431E652DE5B05296C5D42DB4525, sources: [muflone, github] }, { type: archlinux, filename: bluewho-0.2-1-any.pkg.tar.xz, size: 314, md5sum: D1F9E42262E0E70C9E1457DBB5F03B64, sources: [muflone, github] }]
      -
        version: '0.1'
        shortver: v010
        packages: [{ type: source, filename: bluewho-0.1.tar.gz, size: 187, md5sum: E263D2C77B704514FA5C1C97984CFD9D, sources: [muflone, github] }, { type: debian, filename: bluewho_0.1-1_all.deb, size: 175, md5sum: A6F61F7B6E689F583988A56BD02663C1, sources: [muflone, github] }, { type: archlinux, filename: bluewho-0.1-1-any.pkg.tar.xz, size: 164, md5sum: 3C01FE0ECA7D2EB6DD30F7AD1C1F4E3E, sources: [muflone, github] }]
